version: '3.8'

services:
  app:
    # Путь к Dockerfile
    build: .
    # Маппинг портов: внешний:внутренний
    ports:
      - "80:8080"
    # Пробрасываем конфиги томом, чтобы менять их без пересборки образа
    volumes:
      - ./configs:/app/configs
    # Авторестарт при падении
    restart: always
